### PR TITLE
Add golangci-lint configuration and fix linting issues

### PR DESCRIPTION
**Pull request by renatosaksanni**
some ideas to an open discussion #87

### CODE REVIEW

**Comment by negasus** [comment]
Maybe we want to use official golangci action https://github.com/marketplace/actions/golangci-lint ?

**Comment by renatosaksanni** [comment]
> Maybe we want to use official golangci action https://github.com/marketplace/actions/golangci-lint ?

@negasus 
Sure thing. Please check out the current changes using the official golangci action

**Comment by renatosaksanni** [comment]
@negasus  Are we good to go, or is there anything else that needs to be reviewed?

**Comment by negasus** [comment]
Thanks for contribution

**Pull request merged**
